### ISSUE TITLE
KNX Lib and WLED ingetration

### ISSUE THREAD

**Issue by Alex0176** [thorsten-gehrig/KnxTpUart#2]
Hi,

i test with the knx tpuart lib and a d1_mini for wled and run everytime in the problem with the HardwareSerial to Stream casting. 

Did you know whats todo to get the correct constructor from the androino / wled Environment? 

`wled00\../usermods/KNX-Presents/knx-presents.h:42:46: error: cannot allocate an object of abstract type 'Stream'
         knx = KnxTpUart(&(TPUART_SERIAL_CLASS)Serial1, physicalAddress);`

**Comment by thorsten-gehrig** [comment]
unfortunately not.
