### ISSUE TITLE
cannot import Library to Arduino IDE or Arduino IDE Website

### ISSUE THREAD

**Issue by crazy-jackrabbit** [thorsten-gehrig/KnxTpUart#3]
Cannot import Library to Arduino IDE or Arduino IDE Website
Error: 
LIBRARIES THAT COULD NOT BE IMPORTED:
[KnxTpUart] parse library.properties: library.properties not found

**Comment by nerdoc** [comment]
It is even not findable in the libraries within Arduino IDE 2.2.1

[majuss' fork](https://github.com/majuss/KnxTpUart) has at least a few files added to do that - PR, merge?

**Comment by thorsten-gehrig** [comment]
Should be closed since 2 month - missed to close the issue
